spring:
  application:
    name:
      fastfile-be
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${var_dbUsername}
    password: ${var_dbPassword}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: 8080
  address: 0.0.0.0
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${var_keystorePass}
    key-alias: tomcat
    enabled: true
    key-store-type: PKCS12



management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

storage:
  limits:
    free: 21474836480     # 20 GB in bytes
    premium: 107374182400 # 100 GB in bytes